version: '3.8'

services:
  elnour_node:
    build: .
    depends_on:
      - "MongoDB"
    networks:
      - elnour-network

  MongoDB:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ElnourMongoVol:/data/db
    networks:
      - elnour-network

  NginxServer:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - elnour_node
    networks:
      - elnour-network

volumes:
  ElnourMongoVol:


networks:
  elnour-network:
