version: '3.8'

services:
  elnour_node:
    build: .
    depends_on:
      - "MongoDB"
    ports:
      - 2502:2502
    networks:
      - elnour-network

  MongoDB:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ElnourMongoVol:/data/db
    networks:
      - elnour-network


volumes:
  ElnourMongoVol:


networks:
  elnour-network:
